on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Test, Prop Tests, Example Tests

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - macos-latest
          - ubuntu-latest
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl

    steps:
      - name: Install stable toolchain & components
        uses: actions/checkout@v2
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: fuzz tests
        run: |
          ./run.sh
        working-directory: utils/buffer/fuzz


      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Property based testing
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features prop_test

      - name: Build ping-pong-with-noise example
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path examples/ping-pong-with-noise/Cargo.toml

      - name: Build ping-pong-without-noise example
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path examples/ping-pong-without-noise/Cargo.toml

      - name: Build sv1-client-and-server example
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path examples/sv1-client-and-server/Cargo.toml

